### ISSUE TITLE
Make 8 emotion shape keys for `scilly_drophunter` vrm.

### ISSUE THREAD

**Issue by gonnavis** [webaverse-studios/webaverse#140]
Hello, for `scilly_drophunter` vrm, currently many emotions ( shape keys ) not work.
We have `alert`, `angry`, `embarrassed`, `headNod`, `headShake`, `sad`, `surprise`, `victory` 8 emotions in emotion wheel.
But only have `joy`, `angry`, `sorrow`, `fun`, `surprise`, `scar` 6 shape keys in vrm.
Currently only `angry`, `sad(sorrow)`, `surprise` 3 emotions get matched and work.
Avaer said that:
> every emotion in the reactions wheel needs to trigger a face in all avatars, whatever is most appropriate and available ... If the vrm is missing appropriate data then it needs to be added.
> 
> But for this scilly model I thought we had everything? I am pretty sure this model worked before so I don’t know why it is now broken

So please update the `scilly_drophunter` vrm to have 8 corresponding shape keys.

![image](https://user-images.githubusercontent.com/10785634/224830788-d9e12c62-4f78-4207-8ddb-cdd4902b106b.png)
![image](https://user-images.githubusercontent.com/10785634/224830842-301c36ce-ed4c-47b0-b06e-f4fc383567c1.png)

**Comment by avaer** [comment]
Thanks for doing this investigation!

I think those 6 emotes are the standard ones; those seem to be present already, so there is no need to do any more face artwork.

It's fine if the emote wheel doubles up on some of the face emotes -- we can just map as appropriate to the 6 standard ones.

> Currently only angry, sad(sorrow), surprise 3 emotions get matched and work.

I think this is the core of the problem -- a broken mapping somewhere. Since the visemes are present in the VRM, this seems like a code mapping problem, rather than an art problem.

**Comment by gonnavis** [comment]
Okay! Then should just need a new `map`.

**Comment by gonnavis** [comment]
The `map` Guilty made:
```
Victory: Joy 1
Alert: surprise 1
Angry: anger 1
Embarrassed: fun .4, sad .4
Headnod: fun 1
Headshake: anger .4, sad .4
Sad: sad 1
Surprise: surprise 1
```
I'll modify the codes accordingly.

**Comment by gonnavis** [comment]
Fixed by https://github.com/webaverse-studios/webaverse/pull/141
